# Use postgres/example user/password credentials
version: '3.8'

services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gift1234
      POSTGRES_DB: nest_api
    networks:
      - mwaiseghe

networks:
  mwaiseghe: